wad_group_project/storyteller/urls.py
from django.conf.urls import patterns, url
from storyteller import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^story/(?P<story_slug>[\w\-]+)/$', views.story, name='story'),
    url(r'^search/$', views.search, name='search'),
    url(r'^story_room/(?P<storyid>[\w\-]+)/$', views.storyroom, name='storyroom'),
    url(r'^add_story/$', views.add_story, name='add_story'),
    # url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<category_slug>[\w\-]+)/$', views.category, name='category'),
    url(r'^add_profile/', views.register_profile, name = 'add_profile'),
    url(r'^profile/(?P<user_name>[\w\-]+)/$', views.profile, name = 'profile'),
    url(r'^rate_story/$', views.rate_story, name='rate_story'),
)

wad_group_project/wad_group_project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static 
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/storyteller/add_profile'

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^storyteller/', include('storyteller.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

wad_group_project/storyteller/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

from storyteller.serializers import StorySerializer
from swampdragon.models import SelfPublishModel


# This is the User model. It contains the basic information of a user
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    age = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username


# This is the Category model. It contains all the categories.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True)  # So it can be displayed on the url.

    def save(self, *args, **kwargs):
            self.slug = slugify(self.name)
            super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


# This is the Story model. It has the information of the stories.
class Story(SelfPublishModel, models.Model):
    serializer_class = StorySerializer

    title = models.CharField(max_length=128)
    category = models.ForeignKey(Category)  # connection with Category model
    creator = models.CharField(max_length=128)
    story_text = models.TextField()  # Stores large amounts of Text. See django documentation
    contributors = models.ManyToManyField(User, related_name='contributorlist')
    creation_date = models.DateTimeField(auto_now_add=True, editable=False)
    slug = models.SlugField(unique=True)  # So it can be displayed on the url.

    views = models.IntegerField(default=0)
    rating = models.IntegerField(default=0)

    curr_user = models.CharField(max_length=128)
    users = models.ManyToManyField(User)  # Nice way of connected Many to Many without another table.

    ending = models.BooleanField(default=False)
    ended = models.BooleanField(default=False)
    votes_to_end = models.IntegerField(default=0)
    votes_counted = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
            self.slug = slugify(self.id)
            super(Story, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

wad_group_project/storyteller/forms.py
from django import forms
from django.contrib.auth.models import User
from storyteller.models import UserProfile, Story

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('age', 'picture')

class StoryForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Title")
    class Meta:
        model = Story
        fields = ('title', 'category')

wad_group_project/storyteller/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from itertools import chain
from operator import attrgetter
from storyteller.models import Category, Story, UserProfile
from django.db.models import Q, Count
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from storyteller.forms import UserForm, UserProfileForm, StoryForm

def index(request):
    category_list = Category.objects.annotate(num_stories=Count('story')).order_by('-num_stories')[:10]
    completed_story_list_top = Story.objects.filter(ended=True).order_by('-rating')[:10]
    completed_story_list_new = Story.objects.filter(ended=True).order_by('-creation_date')[:10]
    completed_story_list_popular = Story.objects.filter(ended=True).order_by('-views')[:10]
    ongoing_story_list = Story.objects.filter(ended=False, ending=False).order_by('-creation_date')[:10]

    context_dict = {'categories': category_list, 'completed_stories_top': completed_story_list_top, 'completed_stories_popular': completed_story_list_popular,
    'ongoing_stories': ongoing_story_list, 'completed_stories_new': completed_story_list_new, }

    response = render(request,'storyteller/index.html', context_dict)

    return response

def story(request, story_slug):
    context_dict = {}

    try:
        story = Story.objects.get(slug=story_slug, ended=True)
        story.views = story.views + 1
        story.save()
        context_dict['title']=story.title
        context_dict['text']=story.story_text
        context_dict['creator']=story.creator
        context_dict['views']=story.views
        context_dict['story']=story
    except:
        pass

    return render(request, 'storyteller/story.html', context_dict)

def category(request, category_slug):

    context_dict = {}

    try:
        category = Category.objects.get(slug=category_slug)
        context_dict['category_name'] = category.name

        completed_stories = Story.objects.filter(category=category, ended=True)

        context_dict['completed_stories'] = completed_stories

        context_dict['category'] = category

    except Category.DoesNotExist:
        pass

    return render(request, 'storyteller/category.html', context_dict)

def search(request):
    qTerm = request.GET.get('q')
    context_dict = {}
    result_list = []
    completed_story_list = Story.objects.filter(Q(title__icontains=qTerm), ended=True)
    user_list = User.objects.filter(Q(username__icontains=qTerm))
    ongoing_story_list = Story.objects.filter(Q(title__icontains=qTerm), ended=False)

    context_dict['completed_story_list'] = completed_story_list
    context_dict['ongoing_story_list'] = ongoing_story_list
    context_dict['user_list'] = user_list

    return render(request, 'storyteller/search.html', context_dict)

@login_required
def register_profile(request):
    context_dict = {}
    registered = False
    if request.method == 'POST':
        try:
            profile = UserProfile.objects.get(user=request.user)
            profile_form = UserProfileForm(request.POST, instance=profile)
        except:
            profile_form = UserProfileForm(request.POST)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print profile_form.errors
    else:
        profile_form = UserProfileForm()
    context_dict['profile_form'] = profile_form
    context_dict['registered'] = registered
    return render(request, 'registration/profile_registration.html', context_dict)

def profile(request, user_name):
    context_dict = {}
    try:
        user = User.objects.get(username=user_name)
        context_dict['username'] = user
        try:
            contributor_list = Story.objects.filter(contributors=user,ended=True)
            context_dict['contributor_list'] = contributor_list
        except:
            pass
    except:
        pass
    try:
        profile = UserProfile.objects.get(user=user)
        context_dict['profile'] = profile
    except:
        pass
    return render(request, 'storyteller/profile.html', context_dict)

def storyroom(request, storyid):
    try:
        s = Story.objects.get(pk=storyid)
    except:
        return redirect('index')
    if s.ended == True or s.ending == True:
        return redirect('index')
    else:
        return render(request, 'storyteller/room.html', {'storyid': storyid, 'storycategory': s.category.name})

@login_required
def add_story(request):
    context_dict = {}
    if request.method == 'POST':
        story_form = StoryForm(request.POST)
        if story_form.is_valid():
            story = story_form.save(commit = False)
            story.creator = request.user
            story.curr_user = request.user
            story.save()
            return redirect(storyroom, storyid=story.id)
    else:
        story_form = StoryForm()

    return render(request, 'storyteller/add_story.html', {'form': story_form})


@login_required
def rate_story(request):

    story_id = None
    like = 0
    if request.method == 'GET':
        story_id = request.GET['story_id']
        like = int(request.GET['like'])

    likes = 0
    if story_id:
        story = Story.objects.get(id=story_id)

        if story:
            likes = story.rating + like
            story.rating =  likes
            story.save()

    return HttpResponse(likes)

wad_group_project/templates/storyteller/add_story.html
{% extends 'base.html' %}

{% block body_block %}
{% if user.is_authenticated %}
<form id="story_form" method="post" action="/storyteller/add_story/">
  {% csrf_token %}
  {% for field in form.visible_fields %}
  {{ field.errors }}
  {{ field.help_text }}<br/>
  {{ field }}<br/>
  {% endfor %}
  <br/>
  <input class="btn btn-primary" type="submit" name="submit" value="Add Story" />
</form>
{% endif %}
{% endblock %}

wad_group_project/templates/storyteller/category.html
{% extends 'base.html' %}


{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
<div class="page-header">
  <h1>{{ category_name }}</h1>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    {% if category %}
      {% if completed_stories %}
      <ul class="list-group">
        {% for story in completed_stories %}
        <li class="list-group-item"><a href="{% url 'story' story.slug  %}">{{ story.title }}</a></li>
        {% endfor %}
      </ul>
      {% else %}
      <strong>No stories currently in this category.</strong>
      {% endif %}
    {% else %}
      <p>The specified category {{ category_name }} does not exist!</p>
    {% endif %}
  </div>
</div>
{% endblock %}

wad_group_project/templates/storyteller/cats.html
<div class="panel panel-default">
  <div class="panel-heading">Categories</div>
  <div class="panel-body">
    {% if cats %}
    <ul class="list-group">
      {% for cat in cats %}
      {% if cat == act_cat %}
      <li class="list-group-item active">
      {% else %}
      <li class="list-group-item">
      {% endif %}
        <a href="{% url 'category' cat.slug %}">{{ cat.name }} ({{ cat.story_set.count }})</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <strong>No categories!</strong>
    {% endif %}
  </div>
</div>

wad_group_project/templates/storyteller/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Index{% endblock %}

{% block body_block %}

<div class="page-header">
  {% if user.is_authenticated %}
  <h1>Are you ready to write a story, {{ user.username }}?</h1>
  {% else %}
  <h1>Welcome to StoryTeller</h1>
  {% endif %}
</div>

<p>StoryTeller is an interactive, collaborative writing experience. It enables writers to write stories together, adding one sentence at a time.</p>
<br/>
<div class="row placeholders">
  <div class="col-xs-12 col-sm-6 placeholder">
    <div class="panel panel-default">
      <div class="panel-heading">Completed Stories</div>
      <div class="panel-body">
        <div role="tabpanel">
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class=" active"><a href="#top" aria-controls="top" role="tab" data-toggle="tab">Top</a>
            <li role="presentation"><a href="#new" aria-controls="new" role="tab" data-toggle="tab">New</a></li>
            <li role="presentation"><a href="#popular" aria-controls="popular" role="tab" data-toggle="tab">Popular</a></li>
          </ul>

          {% if completed_stories_top %}
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="top">
              <ul class="list-group">
                {% for story in completed_stories_top %}
                <li class="list-group-item"><a href="{% url 'story' story.slug  %}">
                  {{ story.title }} (Rating: {{story.rating}} Created: {{story.creation_date}} Views: {{story.views}} )</a></li>
                {% endfor %}
              </ul>
            </div>
            <div role="tabpanel" class="tab-pane" id="new">
              <ul class="list-group">
                {% for story in completed_stories_new %}
                <li class="list-group-item"><a href="{% url 'story' story.slug  %}">
                  {{ story.title }} (Rating: {{story.rating}} Created: {{story.creation_date}} Views: {{story.views}} )</a></li>
                {% endfor %}
              </ul>
            </div>
            <div role="tabpanel" class="tab-pane" id="popular">
              <ul class="list-group">
                {% for story in completed_stories_popular %}
                <li class="list-group-item"><a href="{% url 'story' story.slug  %}">
                  {{ story.title }} (Rating: {{story.rating}} Created: {{story.creation_date}} Views: {{story.views}} )</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
          {% else %}
          <strong>There are no completed stories yet.</strong>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 placeholder">
    <div class="panel panel-default">
      <div class="panel-heading">Ongoing Stories</div>
      <div class="panel-body">
        {% if ongoing_stories %}
        <ul class="list-group">
          {% for story in ongoing_stories %}
          <li class="list-group-item">
            <span class="badge">{{ story.users.count }} writer(s)</span>
            <a href="{% url 'storyroom' story.id %}">{{ story.title }}</a>
            | {{ story.category.name }}
          </li>
          {% endfor %}
        </ul>
        {% else %}
        <strong>There are no ongoing stories right now. {% if user.is_authenticated %}<a href="{% url 'add_story' %}">Start one!</a>{% endif %}</strong>
        {% endif %}
      </div>
    </div>
  </div>

</div>

{% endblock %}

wad_group_project/templates/storyteller/profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body_block %}
    {% if username %}
        {% if profile %}
            <div class="page-header">
            <h1><span class="label label-primary"> {{username.username}}'s profile</span></h1>
            </div>
            {% if profile.picture %}

              <div class="col-sm-3 col-md-3">
                <div class="thumbnail" >
                <img alt = "User's photo" src = "{{profile.picture.url}}" />
                <div class="caption">
                  {% if profile.age %}
                  <b> Age: {{profile.age}} </b>
                  <br>
                  {% endif %}
                  <b> E-mail: {{username.email}} </b>
                  {% if user.username == username.username %}
                  <p>
                    <a href="{% url 'add_profile' %}" class="btn btn-primary" role="button">Edit</a>
                  </p>
                  {% endif %}
                </div>
              </div>
            </div>

            {% endif %}

            {% if contributor_list %}
                <strong> Stories in which {{username.username}} took part in: </strong>
                {% for entry in contributor_list %}
                                    <li class="list-group-item"><a href="{% url 'story' entry.slug  %}">
                                    {{ entry.title }} (Rating: {{entry.rating}} Created: {{entry.creation_date}} Views: {{entry.views}} )</a></li>
                {% endfor %}
            {%else%}
                <strong>{{username.username}} has not took a part in any story.</strong>
            {%endif%}

            {% else %}
            {% if user.username == username.username %}
            <b> Your profile contains so little information... Please <a href="{% url 'add_profile' %}">update it</a>. </b>
            {% else %}
            <b> Not sufficient information for that user. </b>
            {% endif %}
            {% endif %}
            {% else %}
        <b> User does not exist. </b>
    {% endif %}
{% endblock %}

wad_group_project/templates/storyteller/room.html
{% extends 'base.html' %}

{% load static swampdragon_tags %}

{% block app_block %}data-ng-app="RoomApp"{% endblock %}

{% block title %}{% endblock %}

{% block extra_css %}
<link href="{% static 'css/storyroom/storyroom.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block body_block %}

{% if user.is_authenticated %}

{% verbatim %}
<div data-ng-controller="StoryCtrl">
  <div class="container-fluid" id="storyRoomContents">
    <div class="page-header">
      <h1>{{ story.title }}  <small>{{ category }} | Created by: {{ story.creator }}</small></h1>
    </div>
    <div class="row">
      <div class="container-fluid">
        <div class="col-md-12">
          <p>{{ story.story_text }}</p>
        </div>
      </div>
    </div>
    <div class="row panel col-md-offset-2 col-sm-offset-3" id="sentence-row">
      <div class="col-md-6" id="sentence-input">
        <textarea class="form-control" id="sentence-input-box" rows="3"></textarea>
        <p>
          <button type="button" class="btn btn-default" id="endbutton" data-ng-click="callVote()">Suggest end</button>
          <button type="button" class="btn btn-primary" id="submitbutton" data-ng-click="submit(story)">Submit</button>
        </p>
      </div>
      <div class="col-md-6">
        <p class="text-center"><b>{{ story.curr_user }}</b> taking turn</p>
        <h2 class="text-center"><span class="label label-warning" id="timer">{{ timeLeft }}</span></h2>
      </div>
    </div>
  </div>

  <div class="modal fade" role="dialog" id="endStoryModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">End Story?</h4>
        </div>
        <div class="modal-body">
          <p>A user has elected to end the story with this sentence:</p>
          <div class="well" id="endSentence"></div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" id="modalDontEndButton" data-ng-click="voteDontEnd()">Don't End</button>
          <button type="button" class="btn btn-primary" id="modalEndButton" data-ng-click="voteEnd()">End</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" role="dialog" id="voteWaitingModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <p>Awaiting votes...</p>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" role="dialog" id="endModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Story Ended</h4>
        </div>
        <div class="modal-body">
          <p>This story has ended. Thanks for writing!</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" id="modalEndButton" data-ng-click="returnToHome()">Return</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endverbatim %}

{% else %}
<p>You must be logged in to join a story</p>
{% endif %}

{% endblock %}

{% block extra_scripts %}

{% if user.is_authenticated %}
<script type="text/javascript">
var extStoryId = {{ storyid }};
var username = "{{ user.username }}";
var category = "{{ storycategory }}";
</script>

<!-- AngularJS -->
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.min.js"></script>

<!-- Swampdragon javascript -->
{% swampdragon_settings %}
<script type="text/javascript" src="{% static 'swampdragon/js/dist/swampdragon.min.js' %}"></script>
<script type="text/javascript" src="{% static 'swampdragon/js/dist/datamapper.js' %}"></script>
<script type="text/javascript" src="{% static 'swampdragon/js/angular/services.js' %}"></script>

<!-- BlockUI -->
<script src="http://malsup.github.io/jquery.blockUI.js"></script>

<!-- StoryTeller app -->
<script type="text/javascript" src="{% static 'js/storyroom/app.js' %}"></script>
<script type="text/javascript" src="{% static 'js/storyroom/controllers.js' %}"></script>

{% endif %}

{% endblock %}

{% block side_block %}
{% endblock %}

wad_group_project/templates/storyteller/search.html
{% extends 'base.html' %}

{% block title %}Search results{% endblock %}
{% block body_block %}

    {% if completed_story_list %}
        <strong> Completed stories: </strong>
        {% for story in completed_story_list %}
                            <li class="list-group-item"><a href="{% url 'story' story.slug  %}">
                            {{ story.title }} (Rating: {{story.rating}} Created: {{story.creation_date}} Views: {{story.views}} )</a></li>
        {% endfor %}
    {%else%}
        <strong>No completed stories match your search</strong>
    {%endif%}
    <br>
    {% if user_list %}
        <strong> Users: </strong>
        {% for user in user_list %}
                            <li class="list-group-item"><a href="{% url 'profile' user.username %}">{{user.username}}</a></li>
        {% endfor %}
    {%else%}
        <strong>No users match your search</strong>
    {%endif%}
    <br>
    {% if ongoing_story_list %}
        <strong> Ongoing stories: </strong>
    {% for story in ongoing_story_list %}
                            <li class="list-group-item"><a href="{% url 'storyroom' story.slug %}"> {{ story.title }} Created: {{story.creation_date}}</a></li>
        {% endfor %}
    {%else%}
        <strong>No ongoing stories match your search</strong>
    {%endif%}



{% endblock %}

wad_group_project/templates/storyteller/story.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ title }}{% endblock %}

{% block body_block %}
	{% if title %}
		<h1>{{ title }} <small><a href="{% url 'category' story.category.slug %}">{{ story.category.name }}</a> | Created by: <a href="{% url 'profile' creator %}">{{ creator }}</a></small></h1>
		<div class="panel panel-default">
			<div class="panel-body">
				<p>{{ text }}</p>
			</div>
		</div>
		<p>
			<div class="panel panel-default">
				<div class="panel-body">
					<p><strong id="like_count">{{ story.rating }}</strong> people like this story</p>
					{% if user.is_authenticated %}
					<button id="likes" data-storyid="{{story.completed_story_id}}" data-like=1 class="btn btn-primary" type="button">
                        <span class="glyphicon glyphicon-thumbs-up"></span>
                        Like
                        </button>
                    <button id="dislikes" data-storyid="{{story.completed_story_id}}" data-like=-1 class="btn btn-primary" type="button">
                        <span class="glyphicon glyphicon-thumbs-down"></span>
                        Dislike
                        </button>
					{% endif %}
				</div>
			</div>
		</p>
	{% else %}
    <strong>No such story exists</strong>
	{% endif %}

{% endblock %}